### ISSUE TITLE
Не работает в Morfy 1.1.0

### ISSUE THREAD

**Issue by Awilum** [pafnuty/morfy-less#1]
Не работает в Morfy 1.1.0 -> 1.1.1 -> 1.1.2

**Comment by pafnuty** [comment]
@Awilum спасибо за сообщение!
Постараюсь сегодня проверить.

**Comment by pafnuty** [comment]
Готово https://github.com/pafnuty/morfy-less/commit/788e312e2022397d91a0e5b51376e0e9d063a0fc
